### ISSUE TITLE
Implementation of Meta Regularization on Weights

### ISSUE THREAD

**Issue by YiSyuanChen** [mingzhang-yin/Meta-learning-without-memorization#3]
First of all, I really appreciate that the authors present such great work. And I have a question about the implementations, does the released code include the part of meta regularization on activation? It seems only have the regularization on weights. I'm not sure if it is my misunderstanding, please kindly point me out. Any suggestions would be very appreciated.

**Comment by mingzhang-yin** [comment]
> First of all, I really appreciate that the authors present such great work. And I have a question about the implementations, does the released code include the part of meta regularization on activation? It seems only have the regularization on weights. I'm not sure if it is my misunderstanding, please kindly point me out. Any suggestions would be very appreciated.

Thanks for your interest. The regularization on activation is implemented for the sinusoid regression in the uploaded ipython notebooks.
